### ISSUE TITLE
Model checkpoints from Table 3

### ISSUE THREAD

**Issue by VSehwag** [openai/improved-diffusion#1]
Hi, 

Thanks for releasing the code, especially in PyTorch. I was wondering if you are also planning to release the checkpoints for models from Table 3?

**Comment by unixpickle** [comment]
These models are now listed at the bottom of the README. Let us know if anything doesn't work!

**Comment by VSehwag** [comment]
Thanks a lot for releasing multiple checkpoints. I wonder if the checkpoints correspond to the ema version (since its not clear from their naming whether its ema or non-ema).
