### ISSUE TITLE
Why do you need fp16 utils?

### ISSUE THREAD

**Issue by vedantroy** [openai/improved-diffusion#27]
Hi! What's the reason y'all are using explicit utilities to convert float32 to float16 tensors instead of using `torch.amp`? I'm thinking of building out my own implementation of this repository, using einops, and was curious if this is something I'd need to take into account instead of just using `torch.amp`.

**Comment by taoisu** [comment]
I was about to ask the same thing and I saw this issue; I'm also confused why this fp16_utils exist, wondering if the amp is missing anything the authors need.

**Comment by vedantroy** [comment]
> I was about to ask the same thing and I saw this issue; I'm also confused why this fp16_utils exist, wondering if the amp is missing anything the authors need.

From the authors:
> 3. When we wrote the original codebase, torch's mixed precision library was not mature enough to use. Now it is likely good enough, but we want to make minimal code changes since these repos are intended as research archives.
