### ISSUE TITLE
Classifier guidance or classifer-free guidance?

### ISSUE THREAD

**Issue by MMMMMz** [openai/improved-diffusion#53]
Hi, thanks for your great work!

Recently I have been working on the conditional generation of diffusion models, and I found that it has classifier guidance and classifier-free guidance. For the former, a classifier needs to be pre-trained. But I didn't find this pre-trained classifier in your code. I am a little confused if you are using the classifier-free guidance.

**Comment by shilianghe007** [comment]
Hi!
You can use this project for classifier guidance: https://github.com/openai/guided-diffusion
Hope this can help you.
