### ISSUE TITLE
Run time error when trying to load a model for sampling

### ISSUE THREAD

**Issue by NicolasNerr** [openai/improved-diffusion#57]
Hello, 

I can't manage to sample from a model. When I am trying to do so : 
RuntimeError: Error(s) in loading state_dict for UNetModel:
Missing key(s) in state_dict: XXX
 size mismatch for: XXXX 
 
 This happens when I try to load the model00000.pt 
 
 Do you have an idea how to solve this issue ?

**Comment by NicolasNerr** [comment]
and now this one : RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by ONobody** [comment]
hi ，
Have you solved this problem?

**Comment by gerard-sanroma** [comment]
Facing the same issue here. Was this closed because a solution has been found? Thanks
