### ISSUE TITLE
Training doesn't work properly

### ISSUE THREAD

**Issue by baniasbaabe** [openai/improved-diffusion#6]
When running

`python scripts/image_train.py --data_dir path/to/images $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS`
The code will run for 2 seconds and finish it without creating a /tmp folder or something similar. There isn't any error neither.

**Comment by VLGIN** [comment]
Run ```python datasets/cifar10.py```, for example if you want to train with cifar10 dataset.
And then replace ```path/to/images``` by ```cifar_train``` for training diffusion model.

**Comment by Josh00-Lu** [comment]
> Run `python datasets/cifar10.py`, for example if you want to train with cifar10 dataset. And then replace `path/to/images` by `cifar_train` for training diffusion model.

What's the differences if I directly use path/to/images point to my dataset?

**Comment by ginlov** [comment]
You need to care about the logic which is different from each datasets. Read the code for more detail. Identifying which logic best fit in your case may ensure the quality of model.
________________________________

**Comment by roywang021** [comment]
have u found the answer?

**Comment by imGncrazY** [comment]
maybe you need a gpu?
