### ISSUE TITLE
Gets stuck when initiating training on custom dataset. 

### ISSUE THREAD

**Issue by TheCanMoun10** [openai/improved-diffusion#77]
When executing the following line to train on a custom made dataset with 700 images the execution gets stuck; nothing gets printed to the terminal.

python scripts/image_train.py --data_dir datasets/diffusion_test_set/ --image_size 32 --num_channels 64 --num_res_block 3 --use_checkpoints True --learn_sigma True --diffusion_steps 500 --noise_schedule linear --lr 1e-4 --batch_size 50 export OPENAI_LOGDIR=./improve-diffusion/tests/

Any ideas on what is wrong?

**Comment by pfeducode** [comment]
your batch size is too large, then dataloader can't load so many image,please turn  low your batchsize. i hope  my advice is helpful for you

**Comment by TheCanMoun10** [comment]
Yes i figured that out the moment after i opened this issue, forgot to close it..
