### ISSUE TITLE
Problem with assert statement

### ISSUE THREAD

**Issue by Mirko1998** [openai/improved-diffusion#96]
I tryed to use images of the size 512x512 and ended up in the gaussian_diffusion.py at this assert statement: assert model_output.shape == (B, C * 2, *x.shape[2:])
Why should the channels be twice the size?
My model_output.shape is: torch.Size([1, 3, 512, 512]). Why should it be now (1, 6, 512, 512)?
Can somebody explain why this is needed or what I'm doing wrong? It doesn't work when I comment it out :D 
`assert model_output.shape == (B, C * 2, *x.shape[2:])
AssertionError`
Thanks for your answers :)

**Comment by ImanGoudarzvand** [comment]
> I tryed to use images of the size 512x512 and ended up in the gaussian_diffusion.py at this assert statement: assert model_output.shape == (B, C * 2, *x.shape[2:]) Why should the channels be twice the size? My model_output.shape is: torch.Size([1, 3, 512, 512]). Why should it be now (1, 6, 512, 512)? Can somebody explain why this is needed or what I'm doing wrong? It doesn't work when I comment it out :D `assert model_output.shape == (B, C * 2, *x.shape[2:]) AssertionError` Thanks for your answers :)


Hi Mirko1998,
That's because you set the "ModelVarType" to eigther "LEARNED" or "LEARNED_RANGE",
in this case your model output channels must be doubled (2 * C) , since the last 3 channels are for variance learning.

**Comment by Mirko1998** [comment]
Thank you very much for your answer! That helps me to understand it in more detail 👍

**Comment by Sillyyk** [comment]
> I tryed to use images of the size 512x512 and ended up in the gaussian_diffusion.py at this assert statement: assert model_output.shape == (B, C * 2, *x.shape[2:]) Why should the channels be twice the size? My model_output.shape is: torch.Size([1, 3, 512, 512]). Why should it be now (1, 6, 512, 512)? Can somebody explain why this is needed or what I'm doing wrong? It doesn't work when I comment it out :D Thanks for your answers :)`assert model_output.shape == (B, C * 2, *x.shape[2:]) AssertionError`

may i ask u how to do then？ because i am same with u to use 512*512 and find modelvartype.learned

**Comment by Sillyyk** [comment]
> > I tryed to use images of the size 512x512 and ended up in the gaussian_diffusion.py at this assert statement: assert model_output.shape == (B, C * 2, *x.shape[2:]) Why should the channels be twice the size? My model_output.shape is: torch.Size([1, 3, 512, 512]). Why should it be now (1, 6, 512, 512)? Can somebody explain why this is needed or what I'm doing wrong? It doesn't work when I comment it out :D  Thanks for your answers :)`assert model_output.shape == (B, C * 2, *x.shape[2:]) AssertionError`
> 
> Hi Mirko1998, That's because you set the "ModelVarType" to eigther "LEARNED" or "LEARNED_RANGE", in this case your model output channels must be doubled (2 * C) , since the last 3 channels are for variance learning.

may i ask u how to do then？ because i am same with u to use 512*512 and find modelvartype.learned .plz
